// flow-typed signature: 9f202317fc7753475752af48a5cf60c0
// flow-typed version: <<STUB>>/alexa-sdk_v^1.0.7

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alexa-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'alexa-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'alexa-sdk/lib/alexa' {
  declare module.exports: any;
}

declare module 'alexa-sdk/lib/DynamoAttributesHelper' {
  declare module.exports: any;
}

declare module 'alexa-sdk/lib/response' {
  declare module.exports: any;
}

// Filename aliases
declare module 'alexa-sdk/index' {
  declare module.exports: $Exports<'alexa-sdk'>;
}
declare module 'alexa-sdk/index.js' {
  declare module.exports: $Exports<'alexa-sdk'>;
}
declare module 'alexa-sdk/lib/alexa.js' {
  declare module.exports: $Exports<'alexa-sdk/lib/alexa'>;
}
declare module 'alexa-sdk/lib/DynamoAttributesHelper.js' {
  declare module.exports: $Exports<'alexa-sdk/lib/DynamoAttributesHelper'>;
}
declare module 'alexa-sdk/lib/response.js' {
  declare module.exports: $Exports<'alexa-sdk/lib/response'>;
}
